## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import gmaps.datasets
import numpy as np

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

City_ID     City Country  Max Temp Current Description      Lat       Lng  \
0        4   Atuona      PF     78.08          light rain  -9.8000 -139.0333   
1        5    Vaini      TO     86.16    scattered clouds -21.2000 -175.2000   
2        7  Bairiki      KI     86.00          few clouds   1.3292  172.9752   
3       12  Rikitea      PF     78.62       broken clouds -23.1203 -134.9692   
4       16    Kapaa      US     82.38    scattered clouds  22.0752 -159.3190   

                            Hotel Name  
0                          Villa Enata  
1                  Keleti Beach Resort  
2                Tarawa Boutique Hotel  
3                      People ThankYou  
4  Sheraton Kauai Coconut Beach Resort

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map.
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start_df = vacation_df.loc[(vacation_df["City"] == "Ukiah")]
vacation_end_df = vacation_df.loc[(vacation_df["City"] == "Ukiah")]
vacation_stop1_df = vacation_df.loc[(vacation_df ["City"] == "Laguna")]
vacation_stop2_df = vacation_df.loc[(vacation_df ["City"] == "San Ramon")]
vacation_stop3_df = vacation_df.loc[(vacation_df ["City"] == "Half Moon Bay")]

In [6]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start_df[["Lat", "Lng"]].to_numpy()[0]
end = vacation_end_df[["Lat", "Lng"]].to_numpy()[0]
stop1 = vacation_stop1_df[["Lat", "Lng"]].to_numpy()[0]
stop2 = vacation_stop2_df[["Lat", "Lng"]].to_numpy()[0]
stop3 = vacation_stop3_df[["Lat", "Lng"]].to_numpy()[0]

In [7]:
start, end, stop1, stop2, stop3

(array([  39.1502, -123.2078]),
 array([  39.1502, -123.2078]),
 array([  38.421 , -121.4238]),
 array([  37.7799, -121.978 ]),
 array([  37.4636, -122.4286]))

In [8]:
start = (39.1502, -123.2078)
end = (39.1502, -123.2078)
stop1 = (38.421 , -121.4238)
stop2 = (37.7799, -121.978)
stop3 = (37.4636, -122.4286)

In [9]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# # and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure()
start2end_via_stop1_stop2_stop3 = gmaps.directions_layer(start, end, waypoints=[stop1,stop2,stop3], travel_mode='DRIVING')
fig.add_layer(start2end_via_stop1_stop2_stop3)
fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start_df, vacation_stop1_df, vacation_stop2_df, vacation_stop3_df],ignore_index=True)
itinerary_df

City_ID           City Country  Max Temp Current Description      Lat  \
0      193          Ukiah      US     79.52           clear sky  39.1502   
1      199         Laguna      US     80.44           clear sky  38.4210   
2      440      San Ramon      US     80.38           clear sky  37.7799   
3      302  Half Moon Bay      US     81.88           clear sky  37.4636   

        Lng                                         Hotel Name  
0 -123.2078                                  Hampton Inn Ukiah  
1 -121.4238  Holiday Inn Express & Suites Elk Grove Central...  
2 -121.9780                                 San Ramon Marriott  
3 -122.4286                    The Ritz-Carlton, Half Moon Bay

In [11]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp}</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [12]:
# 11a. Add a marker layer for each city to the map.
fig = gmaps.figure()
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(markers)
# 11b. Display the figure
fig


Figure(layout=FigureLayout(height='420px'))